### ISSUE TITLE
Select default role does not work

### ISSUE THREAD

**Issue by NinoKrb** [KrbDevelopment/Articly-Frontend#3]
**Describe the bug**
Selecting a default role does not work if the role was previously set as default

**To Reproduce**
1. Go to roles page
2. Click on edit role
3. Check the "is default" checkbox
4. Save the changes now
5. Open the edit role modal again
6. Save the role without changes
7. "is default" is now reset to false

**Expected behavior**
That the "is default" value keeps his settings

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Google-Chrome
 - Version: 92.0.4515.107

**Comment by JanKrb** [comment]
Fixed in:

https://github.com/KrbDevelopment/Articly-Frontend/commit/2138d6d24924c040dcf5cad087ea1221bb869ef2
https://github.com/KrbDevelopment/Articly-Frontend/commit/dbc11c9024c5bbc4526f6850c9a22aa322fb303a

Error reason:
Data type mismatch. Backend expected bool, Frontend gave int (either 0 or 1)
